config:
  target: "http://localhost:8080/api"
  phases:
    - duration: 30
      arrivalRate: 1
scenarios:
  - flow:
      - post:
          url: "/auth/login/"
          form:
            username: "admin"
            password: "password123"
          capture:
            headers: "Set-Cookie"
            as: cookie
          expect:
            - statusCode: 200
      - get:
          headers:
            Cookie: "{{ cookie }}"
          url: "/productos/"
